M48
; DRILL file {KiCad 9.0.2} date 2025-07-23T22:01:27-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-23T22:01:27-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
%
G90
G05
T1
X3.4252Y-3.2539
X10.1713Y-5.2244
T2
X3.4724Y-5.1457
X9.8602Y-5.1417
M30
